### ISSUE TITLE
Problem in com.google.firebase:firebase-messaging:9.0.0

### ISSUE THREAD

**Issue by ReginFell** [VictorAlbertos/RxFcm#1]
Hi! Could you update 
com.google.firebase:firebase-messaging:9.0.0
to version 9.0.2+ , because it has issue that crash application on android 6 when try to get FCM token

**Comment by ReginFell** [comment]
https://github.com/VictorAlbertos/RxFcm/pull/2

**Comment by VictorAlbertos** [comment]
Sorry @ReginFell. I don't how but I wasn't "watching" the repository. So I didn't get any notification about this issue.

I've created a new released with your PR:
`compile 'com.github.VictorAlbertos:RxFcm:0.0.2'`

Thanks for the contribution ;)

**Comment by ReginFell** [comment]
Thanks a lot!
