### ISSUE TITLE
Receive notifications when app is killed

### ISSUE THREAD

**Issue by martiwi** [VictorAlbertos/RxFcm#12]
Hello,

Is there a way to configure your library in a way that notifications are received even when application is killed by registering a receiver in the Android Manifest for example ?

Thx.

**Comment by VictorAlbertos** [comment]
Hi @martiwi 

I would not try to change the [standard behaviour](http://stackoverflow.com/questions/24313539/push-notifications-when-app-is-closed) designed by google. But if you need to do that, in the previous link you can find some approaches, but I'm not familiar with them and I'm not willing to provide from RxFcm any kind of workaround for them.
