### ISSUE TITLE
Error:Could not find com.github.VictorAlbertos:RxFcm:0.1.0.

### ISSUE THREAD

**Issue by gergirod** [VictorAlbertos/RxFcm#14]
I'm following the set up as its is in the readme file but I'm getting this Error:Could not find com.github.VictorAlbertos:RxFcm:0.1.0. any idea why?

**Comment by VictorAlbertos** [comment]
That's really weird. From time to time Jitpack does not perform the build properly, but it seems to not be the case that time.

https://jitpack.io/com/github/VictorAlbertos/RxFcm/0.1.0/build.log

Have you add to your top level gradle script the reference to the jitpack repos?

```gradle
allprojects {
    repositories {
        //..
        maven { url "https://jitpack.io" }
    }
} 
```

**Comment by gergirod** [comment]
thanks you can close this issue
