### ISSUE TITLE
Background notifications never call

### ISSUE THREAD

**Issue by gergirod** [VictorAlbertos/RxFcm#15]
I'm doing exaclty what you are saying in this set up but the background notifications class never get called, it there any else i have to do for this class gets call? i saw in you app example that yu have some api services that you send a post yo a url, is that what I'm missing? 
thanks

**Comment by gergirod** [comment]
Any comment to this one?

**Comment by VictorAlbertos** [comment]
That service is just to be able to test the push notifications. They act the way a ser would do it. So no, that is not something that you need to implement.

I can't help you without more details about your configuration.
