### ISSUE TITLE
abstract method "void com.google.firebase.iid.zzb.handleIntent(android.content.Intent)"

### ISSUE THREAD

**Issue by Skullper** [VictorAlbertos/RxFcm#18]
When I have updated my firebase-core and google-play-services libraries to 10.2.4 I encountered with this error when push arrives:
abstract method "void com.google.firebase.iid.zzb.handleIntent(android.content.Intent)"
To fix this you just need to add com.google.firebase:firebase-messaging:+ with the same version as your firebase-core lib.
Victor, can you remove com.google.firebase:firebase-messaging:9.6.0 from rx-fcm library build. And just let us to adding it by ourselves. Thank you.
P.S. don't forget to change the README. Thank you for your beautiful library :)

**Comment by VictorAlbertos** [comment]
Thanks @Skullper for pointing that out. Do you care to submit a PR?

**Comment by Skullper** [comment]
Already done it

**Comment by VictorAlbertos** [comment]
Closed via #19
