### ISSUE TITLE
Bug with Kotlin

### ISSUE THREAD

**Issue by Ornolfr** [VictorAlbertos/RxFcm#20]
When I get a push from server, this line is shown in the logs:
`E/RxGcm: Error thrown from GcmReceiverData subscription. Cause exception: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter key`
It even tells GCM although I use RxFcm:
`compile 'com.github.VictorAlbertos:RxFcm:0.1.0-2.x'`

**Comment by mrArtCore** [comment]
Hello!
First of all, there are not much useful info. Could you give more informarion, please? I mean full stacktrace. 

And other question. How long have you been using Kotlin? 
From the stacktrace we can see, that some param, that, probably,  you specified as non null was null in your subscribtion. In Kotlin, when you work with third party java code, you have to keep in mind fact that your params may be nulls. 
See Kotlin docs for more info.

**Comment by Ornolfr** [comment]
@mrArtCore nope, my code did nothing with this bug. It was an internal bug with the library because it requires a "rx_fcm_key_target" in the push body. Fixed it by asking the server man add such a string to the push body and it worked

**Comment by Ornolfr** [comment]
@mrArtCore maybe annotating the field with @Nullable can do the trick
