### ISSUE TITLE
Make the RX FCM Key Target configurable

### ISSUE THREAD

**Issue by hrougier** [VictorAlbertos/RxFcm#7]
Hi,

Your library is great but unfortunately the target key "rx_fcm_key_target" is not configurable.

I'm not in control of the backend which sends the FCM pushes, so I cannot set this key and use the targeting features of your lib.

What about making this key configurable instead of a private static final String ?
This is a minor and quick change to do, making your library more flexible.

Regards.

**Comment by VictorAlbertos** [comment]
Hi @hrougier 

I'll try to implement it by tomorrow ;)

**Comment by hrougier** [comment]
Hi,

Nice :)

I've forked the lib and made a change so the init() method accepts an optional rxFcmKeyTarget parameters.

**Comment by VictorAlbertos** [comment]
I review your fork and the implementation looks good to me. Why don't you explain in the README this new configuration and perform a pull request? That would be great, thanks ;)

**Comment by VictorAlbertos** [comment]
Available from version 0.0.5

**Comment by kevinthecity** [comment]
This was a great change - I was forking this lib for that exact reason
